# Generated by Django 5.0.4 on 2026-05-03 08:04

import apps.messaging.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageReadReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "message_read_receipts",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("file", "File"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                (
                    "media_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.messaging.models.message_media_path,
                    ),
                ),
                (
                    "media_mime_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "media_file_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "media_file_size",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chats.chat",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
    ]
