# Generated by Django 5.0.4 on 2026-05-03 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0001_initial"),
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmember",
            name="last_read_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="messaging.message",
            ),
        ),
    ]
