# Generated by Django 5.0.4 on 2026-05-03 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="members",
            field=models.ManyToManyField(
                related_name="chats",
                through="chats.ChatMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="groupmeta",
            name="chat",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_meta",
                to="chats.chat",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatmember",
            unique_together={("chat", "user")},
        ),
    ]
